<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            ['nombre' => 'Afganistán'],
            ['nombre' => 'Albania'],
            ['nombre' => 'Alemania'],
            ['nombre' => 'Andorra'],
            ['nombre' => 'Angola'],
            ['nombre' => 'Antigua y Barbuda'],
            ['nombre' => 'Arabia Saudita'],
            ['nombre' => 'Argelia'],
            ['nombre' => 'Argentina'],
            ['nombre' => 'Armenia'],
            ['nombre' => 'Australia'],
            ['nombre' => 'Austria'],
            ['nombre' => 'Azerbaiyán'],
            ['nombre' => 'Bahamas'],
            ['nombre' => 'Bahréin'],
            ['nombre' => 'Bangladés'],
            ['nombre' => 'Barbados'],
            ['nombre' => 'Bélgica'],
            ['nombre' => 'Belice'],
            ['nombre' => 'Benín'],
            ['nombre' => 'Bielorrusia'],
            ['nombre' => 'Birmania'],
            ['nombre' => 'Bolivia'],
            ['nombre' => 'Bosnia y Herzegovina'],
            ['nombre' => 'Botsuana'],
            ['nombre' => 'Brasil'],
            ['nombre' => 'Brunéi'],
            ['nombre' => 'Bulgaria'],
            ['nombre' => 'Burkina Faso'],
            ['nombre' => 'Burundi'],
            ['nombre' => 'Cabo Verde'],
            ['nombre' => 'Camboya'],
            ['nombre' => 'Camerún'],
            ['nombre' => 'Canadá'],
            ['nombre' => 'Chad'],
            ['nombre' => 'Chile'],
            ['nombre' => 'China'],
            ['nombre' => 'Colombia'],
            ['nombre' => 'Comoras'],
            ['nombre' => 'Congo'],
            ['nombre' => 'Corea del Norte'],
            ['nombre' => 'Corea del Sur'],
            ['nombre' => 'Costa Rica'],
            ['nombre' => 'Croacia'],
            ['nombre' => 'Cuba'],
            ['nombre' => 'Dinamarca'],
            ['nombre' => 'Dominica'],
            ['nombre' => 'Ecuador'],
            ['nombre' => 'Egipto'],
            ['nombre' => 'El Salvador'],
            ['nombre' => 'Emiratos Árabes Unidos'],
            ['nombre' => 'Escocia'],
            ['nombre' => 'Eslovenia'],
            ['nombre' => 'España'],
            ['nombre' => 'Estados Unidos'],
            ['nombre' => 'Estonia'],
            ['nombre' => 'Etiopía'],
            ['nombre' => 'Fiji'],
            ['nombre' => 'Filipinas'],
            ['nombre' => 'Finlandia'],
            ['nombre' => 'Francia'],
            ['nombre' => 'Gambia'],
            ['nombre' => 'Georgia'],
            ['nombre' => 'Ghana'],
            ['nombre' => 'Grecia'],
            ['nombre' => 'Groenlandia'],
            ['nombre' => 'Guatemala'],
            ['nombre' => 'Guinea'],
            ['nombre' => 'Guinea-Bisáu'],
            ['nombre' => 'Guyana'],
            ['nombre' => 'Haití'],
            ['nombre' => 'Holanda'],
            ['nombre' => 'Hungría'],
            ['nombre' => 'India'],
            ['nombre' => 'Indonesia'],
            ['nombre' => 'Irak'],
            ['nombre' => 'Irán'],
            ['nombre' => 'Irlanda'],
            ['nombre' => 'Islandia'],
            ['nombre' => 'Islas Malvinas'],
            ['nombre' => 'Islas Marshall'],
            ['nombre' => 'Islas Salomón'],
            ['nombre' => 'Italia'],
            ['nombre' => 'Jamaica'],
            ['nombre' => 'Japón'],
            ['nombre' => 'Jordania'],
            ['nombre' => 'Kazajistán'],
            ['nombre' => 'Kenia'],
            ['nombre' => 'Kirguistán'],
            ['nombre' => 'Kiribati'],
            ['nombre' => 'Kuwait'],
            ['nombre' => 'Laos'],
            ['nombre' => 'Lesoto'],
            ['nombre' => 'Letonia'],
            ['nombre' => 'Líbano'],
            ['nombre' => 'Liberia'],
            ['nombre' => 'Libia'],
            ['nombre' => 'Lituania'],
            ['nombre' => 'Luxemburgo'],
            ['nombre' => 'Malasia'],
            ['nombre' => 'Malawi'],
            ['nombre' => 'Maldivas'],
            ['nombre' => 'Mali'],
            ['nombre' => 'Malta'],
            ['nombre' => 'Marruecos'],
            ['nombre' => 'Mauricio'],
            ['nombre' => 'Mauritania'],
            ['nombre' => 'México'],
            ['nombre' => 'Mónaco'],
            ['nombre' => 'Mongolia'],
            ['nombre' => 'Mozambique'],
            ['nombre' => 'Namibia'],
            ['nombre' => 'Nauru'],
            ['nombre' => 'Nepal'],
            ['nombre' => 'Nicaragua'],
            ['nombre' => 'Níger'],
            ['nombre' => 'Nigeria'],
            ['nombre' => 'Noruega'],
            ['nombre' => 'Nueva Zelanda'],
            ['nombre' => 'Omán'],
            ['nombre' => 'Pakistán'],
            ['nombre' => 'Palaos'],
            ['nombre' => 'Panamá'],
            ['nombre' => 'Paraguay'],
            ['nombre' => 'Perú'],
            ['nombre' => 'Polonia'],
            ['nombre' => 'Portugal'],
            ['nombre' => 'Reino Unido'],
            ['nombre' => 'República Centroafricana'],
            ['nombre' => 'República Checa'],
            ['nombre' => 'República del Congo'],
            ['nombre' => 'República Dominicana'],
            ['nombre' => 'Rumania'],
            ['nombre' => 'Rusia'],
            ['nombre' => 'Samoa'],
            ['nombre' => 'San Cristóbal y Nieves'],
            ['nombre' => 'San Marino'],
            ['nombre' => 'Santa Lucía'],
            ['nombre' => 'Santo Tomé y Príncipe'],
            ['nombre' => 'Senegal'],
            ['nombre' => 'Serbia'],
            ['nombre' => 'Seychelles'],
            ['nombre' => 'Sierra Leona'],
            ['nombre' => 'Singapur'],
            ['nombre' => 'Eslovaquia'],
            ['nombre' => 'Eslovenia'],
            ['nombre' => 'Somalia'],
            ['nombre' => 'Sudáfrica'],
            ['nombre' => 'Sudán'],
            ['nombre' => 'Suecia'],
            ['nombre' => 'Suiza'],
            ['nombre' => 'Siria'],
            ['nombre' => 'Tailandia'],
            ['nombre' => 'Tanzania'],
            ['nombre' => 'Timor Oriental'],
            ['nombre' => 'Togo'],
            ['nombre' => 'Tonga'],
            ['nombre' => 'Trinidad y Tobago'],
            ['nombre' => 'Túnez'],
            ['nombre' => 'Turkmenistán'],
            ['nombre' => 'Turquía'],
            ['nombre' => 'Tuvalu'],
            ['nombre' => 'Uganda'],
            ['nombre' => 'Ucrania'],
            ['nombre' => 'Uruguay'],
            ['nombre' => 'Uzbekistán'],
            ['nombre' => 'Vanuatu'],
            ['nombre' => 'Venezuela'],
            ['nombre' => 'Vietnam'],
            ['nombre' => 'Yemen'],
            ['nombre' => 'Zambia'],
            ['nombre' => 'Zimbabue'],
        ];
        

        DB::table('pais')->upsert($paises, ['nombre'], ['nombre']);
    }
}
